language: php

php:
    - 7.2
    - 7.3
    - 7.4

env:
    - DEPENDENCY_VERSION='--prefer-lowest'
    - DEPENDENCY_VERSION='--prefer-stable'

cache:
    directories:
        - ~/.composer/cache

install:
    - composer update ${DEPENDENCY_VERSION}

script:
    - php vendor/bin/parallel-lint ./src ./tests ./examples
    - php vendor/bin/ecs check --verbose ./src ./tests ./examples
    - php vendor/bin/phpunit
