language: php

php:
    - 7.1
    - 7.2
    - 7.3

cache:
    directories:
        - ~/.composer/cache

before_install:
    - composer self-update --1

install:
    - composer install

script:
    - php vendor/bin/parallel-lint ./src ./tests ./examples
    - php vendor/bin/ecs check --verbose ./src ./tests ./examples
    - php vendor/bin/phpunit
